spring:
  application:
    name: multiple-datasources
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    posts:
      jdbc-url: jdbc:mysql://localhost:3306/post?createDatabaseIfNotExist=true
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
    comments:
      jdbc-url: jdbc:h2:mem:comment?createDatabaseIfNotExist=true
      username: sa
      password:
      driver-class-name: org.h2.Driver
      h2:
        console.enabled: true
#  main:
#    allow-circular-references: true